[0m02:59:04.039750 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78ae610b07c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78ae5f7b9b70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78ae5f7b9b10>]}


============================== 02:59:04.043864 | 388a3875-d9d6-43c0-95d2-c1e6668120bf ==============================
[0m02:59:04.043864 [info ] [MainThread]: Running with dbt=1.8.0
[0m02:59:04.044483 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init demo_dbt_project', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m02:59:04.051097 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/vscode/.dbt')}
[0m02:59:04.051841 [info ] [MainThread]: Creating dbt configuration folder at 
[0m02:59:04.053094 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m02:59:04.055988 [info ] [MainThread]: 
Your new dbt project "demo_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m02:59:04.056517 [info ] [MainThread]: Setting up your profile.
[0m05:13:40.371954 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b24f606d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b23815bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b23815b70>]}


============================== 05:13:40.375454 | 42a4761a-9d3c-42c4-8551-0c3d5a13dfd6 ==============================
[0m05:13:40.375454 [info ] [MainThread]: Running with dbt=1.8.0
[0m05:13:40.376123 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m05:13:40.376638 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:13:40.377477 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04899446, "process_user_time": 1.046004, "process_kernel_time": 0.091129, "process_mem_max_rss": "84180", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m05:13:40.378060 [debug] [MainThread]: Command `dbt run` failed at 05:13:40.377960 after 0.05 seconds
[0m05:13:40.378443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b24f606d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b23815c60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x741b23815ba0>]}
[0m05:13:40.378839 [debug] [MainThread]: Flushing usage events
[0m05:51:57.828534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96f000760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96d8c1c60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96d8c1c00>]}


============================== 05:51:57.833136 | 9c7441b2-f470-491d-9f07-39fd0fddbff2 ==============================
[0m05:51:57.833136 [info ] [MainThread]: Running with dbt=1.8.0
[0m05:51:57.833923 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:51:57.834526 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:51:57.835434 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04952924, "process_user_time": 1.051465, "process_kernel_time": 0.154269, "process_mem_max_rss": "83648", "process_in_blocks": "66968", "process_out_blocks": "8", "command_success": false}
[0m05:51:57.835987 [debug] [MainThread]: Command `dbt run` failed at 05:51:57.835890 after 0.05 seconds
[0m05:51:57.836375 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96f000760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96d8c1cf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e96d8c1c30>]}
[0m05:51:57.836764 [debug] [MainThread]: Flushing usage events
[0m19:37:46.560357 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763446c18760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763445325c30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763445325bd0>]}


============================== 19:37:46.564796 | 63ffd88d-f278-4eae-8e6a-7481935fda31 ==============================
[0m19:37:46.564796 [info ] [MainThread]: Running with dbt=1.8.0
[0m19:37:46.565646 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:37:46.566399 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:37:46.567372 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.055598628, "process_user_time": 1.089696, "process_kernel_time": 0.162641, "process_mem_max_rss": "83896", "process_in_blocks": "58488", "process_out_blocks": "16", "command_success": false}
[0m19:37:46.568032 [debug] [MainThread]: Command `dbt run` failed at 19:37:46.567928 after 0.06 seconds
[0m19:37:46.568460 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763446c18760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763445325cc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763445325c00>]}
[0m19:37:46.568938 [debug] [MainThread]: Flushing usage events
[0m13:30:33.689355 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d02860760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d00f79b70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d00f79b10>]}


============================== 13:30:33.693765 | a5e0b2cf-c29d-4ba6-bdb3-a03008f36776 ==============================
[0m13:30:33.693765 [info ] [MainThread]: Running with dbt=1.8.0
[0m13:30:33.694528 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select customer_order_summarry', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:30:33.695050 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:30:33.695996 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.05321749, "process_user_time": 1.014344, "process_kernel_time": 0.080185, "process_mem_max_rss": "84000", "process_in_blocks": "240", "process_out_blocks": "8", "command_success": false}
[0m13:30:33.696599 [debug] [MainThread]: Command `dbt run` failed at 13:30:33.696498 after 0.05 seconds
[0m13:30:33.697022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d02860760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d00f79c00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7d00f79b40>]}
[0m13:30:33.697417 [debug] [MainThread]: Flushing usage events
[0m13:31:19.120086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79371af54700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793719815c00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793719815ba0>]}


============================== 13:31:19.123824 | 65500c41-087f-48b6-bd77-a32dd416299a ==============================
[0m13:31:19.123824 [info ] [MainThread]: Running with dbt=1.8.0
[0m13:31:19.124583 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m13:31:19.125135 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:31:19.125995 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.052977078, "process_user_time": 1.068706, "process_kernel_time": 0.059815, "process_mem_max_rss": "83912", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m13:31:19.126579 [debug] [MainThread]: Command `dbt run` failed at 13:31:19.126478 after 0.05 seconds
[0m13:31:19.126988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79371af54700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793719815c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x793719815bd0>]}
[0m13:31:19.127520 [debug] [MainThread]: Flushing usage events
[0m15:28:38.982080 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff797847f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff77e99c00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff77e99ba0>]}


============================== 15:28:38.985622 | 5c59c20d-29e5-43e6-bb8a-6a7654c8e73a ==============================
[0m15:28:38.985622 [info ] [MainThread]: Running with dbt=1.8.0
[0m15:28:38.986826 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:28:38.987392 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:28:38.988334 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.051334113, "process_user_time": 1.057895, "process_kernel_time": 0.210023, "process_mem_max_rss": "83424", "process_in_blocks": "66960", "process_out_blocks": "8", "command_success": false}
[0m15:28:38.989049 [debug] [MainThread]: Command `dbt run` failed at 15:28:38.988941 after 0.05 seconds
[0m15:28:38.989442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff797847f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff77e99c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7aff77e99bd0>]}
[0m15:28:38.989844 [debug] [MainThread]: Flushing usage events
[0m21:21:25.334781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d5134790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d387b7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d387b850>]}


============================== 21:21:25.343519 | ff191537-d255-460f-8f78-680a5cb674b7 ==============================
[0m21:21:25.343519 [info ] [MainThread]: Running with dbt=1.8.0
[0m21:21:25.344296 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt test -m source', 'send_anonymous_usage_stats': 'True'}
[0m21:21:25.344913 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:21:25.345834 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.058093533, "process_user_time": 1.079469, "process_kernel_time": 0.170651, "process_mem_max_rss": "83584", "process_in_blocks": "66992", "process_out_blocks": "8", "command_success": false}
[0m21:21:25.346423 [debug] [MainThread]: Command `dbt test` failed at 21:21:25.346326 after 0.06 seconds
[0m21:21:25.346805 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d5134790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d387abf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff4d387b820>]}
[0m21:21:25.347211 [debug] [MainThread]: Flushing usage events
[0m17:54:25.376144 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1199a8ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1198b9d450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1198b9c430>]}


============================== 17:54:25.381650 | 0962bec0-4737-45b1-b49a-6b98685fa15f ==============================
[0m17:54:25.381650 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:54:25.382368 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt snapshot', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:54:25.382893 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-leo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:54:25.384431 [debug] [MainThread]: Resource report: {"command_name": "snapshot", "command_success": false, "command_wall_clock_time": 0.06326307, "process_in_blocks": "75008", "process_kernel_time": 0.231144, "process_mem_max_rss": "91172", "process_out_blocks": "16", "process_user_time": 1.296021}
[0m17:54:25.384964 [debug] [MainThread]: Command `dbt snapshot` failed at 17:54:25.384854 after 0.06 seconds
[0m17:54:25.385414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1199a8ded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1198b9e080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1198b9d420>]}
[0m17:54:25.385849 [debug] [MainThread]: Flushing usage events
[0m17:54:25.585751 [debug] [MainThread]: An error was encountered while trying to flush usage events
